[package]
name = "handler"
version = "0.1.0"
authors = ["captain-yossarian <sergiybiluk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = "0.2"
tokio = { version = "0.2", features = ["full"] }